openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/jobss:
    x-router-controller: jobsController
    get:
      description: Returns all jobss
      operationId: getJobss
      responses:
        200:
          description: Jobs list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      description: Creates a new team
      operationId: addTeam
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobs'
        description: Team to be created
        required: true
      responses:
        201:
          description: Team
        default:
            description: Unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'
                  
  /api/v1/jobss/{province}:
    x-router-controller: jobsController
    get:
      description: Returns a single team by its jobs
      operationId: findByprovince
      parameters:
        - required: true
          name: id
          description: id of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Team found by jobs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      description: Update a team based on its id
      operationId: updateTeam
      parameters:
        - required: true
          name: id
          description: id of the team to update
          in: path
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobs'
        description: Team to be updated
        required: true
      responses:
        '204':
          description: Jobs updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      description: Deletes a single team based on its id
      operationId: deleteTeam
      parameters:
        - required: true
          name: id
          description: id of the team to delete
          in: path
          schema:
            type: number
      responses:
        '204':
          description: Team deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    jobs:
        type: object
        required:
          - province
        properties:
          province:
            type: string
          year:
            type: number
          gender:
            type: string
          low_due_to_placement:
            type: number
          no_renovation:
            type: number
          other_reason:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true